baseURL = "https://bayura199.github.io/"

theme = "LoveIt"

# judul website (muncul di tab browser)
title = "MyArsip"

# kode bahasa ["id", "zh-CN", "fr", "pl", ...]
languageCode = "id"

# nama bahasa ["Indonesia", "简体中文", "Français", "Polski", ...]
languageName = "Indonesia"

# Konfigurasi menu
[menu]

  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""

  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""

  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

  [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""

[params]
  title = "Arsip Diri"
  subtitle = "Arsip Diri"
  favicon = "images/image.jpg" # favicon untuk tab browser (png/jpg)

  [params.header]
    # mode header di desktop ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mode header di mobile ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Konfigurasi judul/header di pojok kiri atas
    [params.header.title]
      # URL logo (kalau ingin pakai logo gambar)
      logo = ""
      # nama judul yang tampil di header
      name = "My Arsip"
      # pakai pre untuk icon di kiri teks (icon - teks)
      pre = "<i class='fas fa-folder-open'></i>&nbsp;"
      # pakai post untuk icon di kanan teks (teks - icon)
      post = ""
      # aktifkan animasi efek ketik (typewriter) pada nama
      typeit = false

  [params.home.profile]
    title = "Arsip Diri"
    enable = true
    name = "Bayu Anggara"
    avatarURL = "images/image.jpg"
    subtitle = "Sebuah Perjalanan Untuk Menemukan Satu Tujuan Pasti.."
    typeit = true
    social = true

  [params.app]
    noFavicon = false

  [params.social]
    GitHub = "bayura199"
    Linkedin = "bayu-anggara-592020215/"
    Instagram = "bayura199"
    Facebook = "bayu.anggara.871412"
    Telegram = "bayura199"
    Email = "bayura1709@gmail.com"

  [params.search]
    enable = true
    type = "lunr"  # atau bisa juga "fuse"
    contentLength = 4000
    placeholder = "Search..."
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = true

  [params.footer]
    enable = true           # aktifkan tampilan footer
    hugo = true             # tampilkan "Powered by Hugo & LoveIt"
    copyright = true        # tampilkan informasi copyright
    since = 2024            # tahun mulai (contoh: "2024 - 2025")
    author = true           # tampilkan nama penulis
    license = ""            # opsional (kosongkan jika tidak ada lisensi khusus)
    icp = ""                # dibiarkan kosong jika tidak digunakan

  # Nama penulis ditentukan di sini
  [params.author]
    name = "Bayu Anggara"
    link = "/"

  [params.page.share]
  enable = true

  # -- Platform yang diaktifkan --
  Facebook = true
  Instagram = true
  Linkedin = true
  Whatsapp = true
  Line = true
  Reddit = true
  Telegram = true
  Pinterest = true

  # -- Platform yang dimatikan --
  Tumblr = false
  HackerNews = false
  VK = false
  Buffer = false
  Xing = false
  Instapaper = false
  Pocket = false
  Flipboard = false
  Weibo = false
  Blogger = false
  Baidu = false
  Odnoklassniki = false
  Evernote = false
  Skype = false
  Trello = false
  Diaspora = false
  Mix = false

[markup]
  # Penyorotan sintaks (untuk code block)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false adalah konfigurasi wajib
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  # Goldmark adalah library markdown default dari Hugo 0.60 ke atas
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # apakah akan izinkan penggunaan HTML langsung di markdown
      unsafe = true

  # Pengaturan Table Of Contents (Daftar Isi)
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Konfigurasi sitemap
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Konfigurasi permalink (tautan tetap)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Konfigurasi privasi
[privacy]
  # LoveIt DIUBAH | 0.3.1 pengaturan privasi Google Analytics (bisa juga diatur di params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    # ...
  [privacy.youtube]
    # ...

# Konfigurasi output file .md
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Konfigurasi output format untuk file markdown
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Konfigurasi output Hugo
[outputs]
  # LoveIt DIUBAH | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
